### ISSUE TITLE
Support tagged literals

### ISSUE THREAD

**Issue by sgrove** [gstamp/align-cljlet#7]
Right now align-cljlet will fail if a let binding form includes e.g. `[val #js[1 2 3]]`, thinking that there are multiple pairs on the same line. Would be great to have support for this, but not sure how much of a change it would be.

**Comment by arrdem** [comment]
I think the issue here as in my "ignore metadata" patch is that you've got to start implementing a Clojure "forward-sexp" that's got all kinds of nasty corner cases. You could support this easily enough by adding more code to my `acl-forward-sexp` or some equivalent fn to, given `#` walk forwards one character and then two sexps. Maybe some magic required for `#_` as well.
